version: "3.3"
services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./qdrant_data:/qdrant/storage

  avm-demo:
    image: amv-demo
    build:
      context: .
      dockerfile: dockerfiles/demo/Dockerfile
    environment:
      NVIDIA_DISABLE_REQUIRE: 1
    ports:
      - 8501:8501
    expose:
      - 8501
    volumes:
      - ./data:/lct_rutube/data

