version: "3.3"
services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant/storage

  avm-demo:
    image: amv-demo
      build:
        context: .
        dockerfile: dockerfiles/demo/Dockerfile
    volumes:
      - ./data:/lct_rutube/data

